# Generated by Django 4.0 on 2021-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='date_posted',
        ),
    ]
